# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://blowfish.page/docs/getting-started/

theme = "blowfish"
baseURL = "https://archive-2025.lab.gb0.dev"
defaultContentLanguage = "zh-CN"
timezone = "Asia/Shanghai"

timeout = "180s" # regress the build failure #1595

pluralizeListTitles = "true" # hugo function useful for non-english languages, find out more in  https://gohugo.io/getting-started/configuration/#pluralizelisttitles
hasCJKLanguage = true

enableRobotsTXT = true
#paginate = 10
summaryLength = 0

buildDrafts = false
buildFuture = false

# googleAnalytics = "G-XXXXXXXXX"

enableEmoji = true


[permalinks]
  [permalinks.page]
    posts = '/post/:slug/'
    pages = ':slugorcontentbasename/'

  [permalinks.section]
    posts = '/posts/'

[imaging]
  anchor = 'Center'

[taxonomies]
  tag = "tags"
  category = "categories"
  author = "authors"
  series = "series"

[sitemap]
  changefreq = 'daily'
  filename = 'sitemap.xml'
  priority = 0.5

[outputs]
  home = ["HTML", "JSON","jsonfeed","twtxt","fed"]

[mediaTypes."application/feed+json"]
    suffixes = [ "json" ]

[mediaTypes."application/rss+xml"]
    suffixes = [ "rss", "xml" ]

[outputFormats]
    [outputFormats.jsonfeed]
        mediaType = "application/feed+json"
        baseName = "feed"
        rel = "alternate"
        isPlainText = true

    [outputFormats.twtxt]
        name = "twtxt"
        mediaType = "text/plain"
        baseName = "twtxt"

    # fed.brid.gy only recognize .rss/.atom so make a rss file w/ posts only for it
    [outputFormats.fed]
        name = "fed"
        mediaType = "application/rss+xml"
        baseName = "feed"
        rel = "alternate"
        isPlainText = true


[related]
  threshold = 0
  toLower = false

    [[related.indices]]
        name = "tags"
        weight = 100

    [[related.indices]]
        name = "categories"
        weight = 100

    [[related.indices]]
        name = "series"
        weight = 50

    [[related.indices]]
        name = "authors"
        weight = 20

    [[related.indices]]
        name = "date"
        weight = 10

    [[related.indices]]
      applyFilter = false
      name = 'fragmentrefs'
      type = 'fragments'
      weight = 10
