languageCode = "zh-CN"
languageName = "中文(简体)"
weight = 1
#title = "Mare_Infinitus"
title = "/var/log/gblab"

[params]
  displayName = "中"
  isoCode = "zh-CN"
  rtl = false
  dateFormat = "2006年1月2日"
  logo = "img/logo@small.png"
  # secondaryLogo = "img/logo.png"
  # description = "某不知名奇点观察员的观察日志"
  description = "此处会不定时产生包含大量废话的日志文件"
  copyright = "© 2024 by 草方块, Under CC-BY-NC-SA 4.0"

 [params.author]
   name = "草方块"
   image = "img/avatar.png"
   headline = "还没取正经名字的折腾怪物"
   bio = "不知名CV工程师，卑微奇点观察员，人类资格证绝赞重考中"
   links = [
     { email = "mailto:hi@imgb.space" },
     { link = "https://imgb.space/" },
     { github = "https://github.com/GrassBlock1" },
     { mastodon = "https://o3o.ca/@grassblock" },
     { steam = "https://steamcommunity.com/profiles/76561199422870469" },
     { telegram = "https://t.me/Grass_block" },
     { x-twitter = "https://twitter.com/Grass_block_cn" },
     { pgpkey = "/gpg-key" },
     { rocket = "https://www.travellings.cn/go.html"}
   ]
