name: Deplo To Github Pages

on:
  # 允许手动push触发
  push:
    branches:
      - master
  workflow_dispatch:
  # 允许外部仓库事件触发
  repository_dispatch:
    types:
      # api中的event_type就是这个
      - deploy
  schedule:
    - cron: 0 0 * * *
    - cron: 0 13 * * *

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 检查分支
        uses: actions/checkout@master

      - name: 安装node环境
        uses: actions/setup-node@master
        with:
          node-version: "16.x"

      - name: 安装pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: |
            - recursive: true
              args: [--frozen-lockfile, --strict-peer-dependencies]
            - args: [--prod]

      - name: 设置时区
        run: |
          export TZ='Asia/Shanghai'

      - name: 拉取Notion的文章
        env:
          # Notion相关环境变量
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
        run: |
          # 对应package.json中的script.sync
          pnpm run sync

      - name: 配置Git用户名邮箱
        run: |
          git config --global user.name "GB-0"
          git config --global user.email "bot@imgb.space"

      - name: 提交拉取的文章到GitHub仓库
        run: |
          git add .
          git commit -m "update from notion" -a

      - name: 推送文章到仓库
        uses: ad-m/github-push-action@master
        with:
          # GITHUB_TOKEN为流水线内置变量，无需配置，可直接使用
          github_token: ${{ secrets.GITHUB_TOKEN }}